---
abstract: 'TMX interface with Open Corpus Workbench'
author:
  - 'Alberto Simoes <ambs@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-TMX-CWB
provides:
  XML::TMX::CWB:
    file: lib/XML/TMX/CWB.pm
    version: 0.04
requires:
  CWB::CL: 2.002102
  Lingua::PT::PLNbase: 0.21
  XML::TMX: 0.17
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
